# Generated by Django 5.2.3 on 2025-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='clan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
